version: 1.0.{build}
os: Visual Studio 2017
test: off
clone_folder: C:\projects\fish_deformation
branches:
  only:
    - master
    - michael
install:
  - git submodule update --init --recursive
  - cinstall: python
build:
  parallel: true
build_script:
  - echo Running cmake ..
  - cd c:\tools\vcpkg
  - .\vcpkg.exe --triplet x64-windows install mpir mpfr
  - cd c:\projects\fish_deformation
  - set PATH=C:\Python%PYTHON%-x64;C:\Python%PYTHON%-x64\Scripts;%PATH%
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64"
      -DCMAKE_PREFIX_PATH="C:/Qt/5.10.1/msvc2017_64/lib/cmake"  
      -DMPFR_INCLUDE_DIR:PATH="C:/tools/vcpkg/installed/x64-windows/include" 
      -DMPFR_LIBRARIES:FILEPATH="C:/tools/vcpkg/installed/x64-windows/lib/mpfr.lib" 
      -DGMP_INCLUDE_DIR:PATH="C:/tools/vcpkg/installed/x64-windows/include" 
      -DGMP_LIBRARIES:FILEPATH="C:/tools/vcpkg/installed/x64-windows/lib/mpir.lib" 
      -DBOOST_ROOT="C:/Libraries/boost_1_65_1" ../
  - msbuild %MSBuildOptions% fish_deformation.sln
after_build:
  - cd C:\Qt\latest\msvc2017_64\bin
  - windeployqt c:\projects\fish_deformation\build\src\Debug\unwind.exe
  - cd C:\projects\fish_deformation
  - 7z a plugins.zip C:\projects\fish_deformation\build\src\Debug\*.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\iconengines\qsvgicon.dll		
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qgif.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qicns.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qico.dll	
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qjpeg.dll	
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qsvg.dll	
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qtga.dll	
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qtiff.dll	
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qwbmp.dll	
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\imageformats\qwebp.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\platforms\qwindows.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\plugins\styles\qwindowsvistastyle.dll 
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\bin\d3dcompiler_47.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\bin\libEGL.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\bin\libGLESV2.dll
  - 7z a plugins.zip C:\Qt\latest\msvc2017_64\bin\opengl32sw.dll
artifacts:
  - path: plugins.zip 
